[project]
name = "pymc-extras"
version = "0.1.0"
description = "PyMC extras project"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
pymc = "*"
scikit-learn = "*"
better-optimize = "*"
python = ">=3.11"
jax = ">=0.7.0,<0.8"
jaxlib = ">=0.7.0,<0.8"
blackjax = ">=1.2.4,<2"
numba = ">=0.56.0"
pre-commit = ">=4.3.0,<5"

# Test environment with additional testing dependencies
[feature.test.dependencies]
pytest = ">=6.0"
pytest-mock = "*"
dask = "<2025.1.1"
xhistogram = "*"
statsmodels = "*"
preliz = ">=0.5.0"
pydantic = ">=2.0.0"
coverage = "*"
pytest-cov = "*"
pytest-xdist = "*"  # for parallel test execution

[environments]
default = ["default"]
test = ["default", "test"]

[tasks]
# Run all tests
test = "pytest tests/"

# Run tests with coverage
test-cov = "pytest tests/ --cov=pymc_extras --cov-report=html --cov-report=term"

# Run tests in parallel
test-parallel = "pytest tests/ -n auto"

# Run specific test files
test-distributions = "pytest tests/distributions/"
test-model = "pytest tests/model/"
test-statespace = "pytest tests/statespace/"

# Run tests with verbose output
test-verbose = "pytest tests/ -v"

# Run a specific test file
test-file = "pytest"

# Clean up test artifacts
clean-test = "rm -rf .coverage htmlcov/ .pytest_cache/ **/__pycache__/"
